### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Blueletric** [AllTheMods/ATM3-Expert#1]
##Leave your mod suggestions below for review and we'll consider adding them in!

 **Oly put in**: 
Nether Ores

**Currently in**:
IC2 Classic
IC2 Extras
Cosmetic Armor Reworked

**Under review**:~

**Comment by Trinsdar** [comment]
If ic2 is going to be used then perhaps use these instead experimental:
[Ic2 Classic](https://minecraft.curseforge.com/projects/ic2-classic)
[Ic2c Extras](https://minecraft.curseforge.com/projects/ic2c-extras)
[Ic2c Addons](https://minecraft.curseforge.com/projects/ic2c-addons)
[Gravisuit Classic](https://minecraft.curseforge.com/projects/gravisuit-classic)
[Advanced Solars Classic](https://minecraft.curseforge.com/projects/advanced-solars-classic)
As for crafttweaker support there is [this](https://minecraft.curseforge.com/projects/ic2-tweaker) and [this](https://github.com/Trinsdar/IC2ClassicTweaker) which I'll be releasing on curseforge once the next ic2 classic patch comes out. When it releases I'll edit this message to put in the curseforge link.

**Comment by Trinsdar** [comment]
[Little Tiles](https://minecraft.curseforge.com/projects/littletiles) Basically like chisel and bite but on steroids in that it can do so much more. It is also completely compatible with chisel and bits. [Reddit post with video series link](https://www.reddit.com/r/feedthebeast/comments/bct8bs/like_chisels_and_bits_want_to_do_the_same_and/?utm_medium=android_app&utm_source=share)

**Comment by SpeedSlider** [comment]
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked

I like this mod in ATM3 as it just gives you the ability to customize your look and have good armor.

**Comment by oly2o6** [comment]
Ill add it for consideration

**Comment by Tfarcenim** [comment]
https://minecraft.curseforge.com/projects/mod-name-tooltip
Adds the name of what mod an item came from to the tooltip

https://minecraft.curseforge.com/projects/tool-helper
Adds mining level info to the tooltip of most tools

https://minecraft.curseforge.com/projects/dense-neutron-collectors if avaritia is present
adds additional tiers of neutron collectors which can help with the main problem of neutron farming:
waiting time and server lag.

https://minecraft.curseforge.com/projects/click-machine
like mechanical user but without needing exu2 which seems to be discontinued

https://minecraft.curseforge.com/projects/extra-anvils
better anvils without modifying the base one

https://minecraft.curseforge.com/projects/unstable-tools
explosive fun

**Comment by oly2o6** [comment]
We have a different mod for tool helper
Mod name tooltip is in
We decided to keep xu2 but it’s not heavily relied on progression wise 
Extra anvils most likely won’t be added 
Unstable tools is on my list of maybe adding 

Can you message me on discord please? Would really like to get you onboard as a tester so you can see what’s already in and help find the bugs in progression
