### ISSUE TITLE
All tree's breakable without axe

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#10]
You can break it with your fist, you take damage but you can break it and it gives you planks, breaks progression.

## Expected Behavior
Unbreakable and deals damage on hitting as do other tree's

## Current Behavior

Breakable but you take damage

## Possible Solution

Make it unbreakable without an axe

**Comment by drizzs** [comment]
I lied turns out you can break any wood with your fist!

**Comment by oly2o6** [comment]
Intended
