### ISSUE TITLE
Can't make elementium processors in the circuit etcher

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#104]
All processors can be made in the ME Circuit Etcher except the elementium one.

Also, I think the recipe is wrong. The redstone is in the middle for every other processor recipe, but for the elementium one the circuit is in the middle and the redstone is on the top.

Oh, and the elementium circuit is named "item.contenttweaker.elementiumprint.name" instead of uh, Elementium Circuit. The elementium processor is fine, though
![Screen Shot 2019-11-13 at 9 41 22 AM](https://user-images.githubusercontent.com/52458743/68773567-cc408f00-05f9-11ea-82cf-6442797dee34.png)

![Screen Shot 2019-11-13 at 9 38 03 AM](https://user-images.githubusercontent.com/52458743/68773325-5fc59000-05f9-11ea-85b0-d1d40b4b4322.png)
![Screen Shot 2019-11-13 at 9 38 15 AM](https://user-images.githubusercontent.com/52458743/68773332-60f6bd00-05f9-11ea-9418-30ee4f168ea7.png)

**Comment by TheGoldCrayon** [comment]
fixed in current version
