### ISSUE TITLE
Can't get fermium

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#106]
Fermium is used for the elven gateway core, the fermium ingots can only be obtained by putting fermium (as an element) in the chemical combiner. the element can't be obtained either- the only recipe for it would be with a fusion controller, but the controller requires alfglass and dragonstones, which need the elven gateway core.
![Screen Shot 2019-11-13 at 9 26 23 PM](https://user-images.githubusercontent.com/52458743/68821632-de074e00-065c-11ea-9cb3-4d2a324d8b6a.png)
![Screen Shot 2019-11-13 at 9 26 28 PM](https://user-images.githubusercontent.com/52458743/68821633-de074e00-065c-11ea-86fb-aa12cbe0ab66.png)

**Comment by oly2o6** [comment]
There is supposed to be an alternate chemical recipe for fermium I’ll add it to dev and update tonight

**Comment by MrMehano** [comment]
still not working :/

**Comment by TheGoldCrayon** [comment]
this has been fixed for some time.

**Comment by MrMehano** [comment]
ok sorry i see it :D
