### ISSUE TITLE
Tier 1 has 7 tears

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#110]
the arcade description says you get 6 tears per tier, but you actually get 7 in tier 1

Have you ever wanted to be a Bontanist # 39 (btw... "bo**n**tanist"?) gives one;
Time to make an oven # 29 gives one;
Machine casing # 59 gives one;
Bat Box # 54 gives one;
Nether # 46 gives three.

**Comment by oly2o6** [comment]
//Remove typo
//remove one tier
