### ISSUE TITLE
working through the machines #216 doesn't detect the machines

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#112]
I made all the machines the exact same way, but it only detected the metallurgic infuser.

Also, since mek machines can be charged from the inventory it's probably better to use outputs from the machines to complete the quest instead of the machines themselves.
![Screen Shot 2019-11-17 at 8 54 06 PM](https://user-images.githubusercontent.com/52458743/69019056-ee7d3880-097c-11ea-8512-cd374660f7dd.png)

Electrolytic separator: no idea why it's not detecting, it has the same NBT
Quest: ![Screen Shot 2019-11-17 at 8 37 17 PM](https://user-images.githubusercontent.com/52458743/69019019-d7d6e180-097c-11ea-9266-1de25a7b5c49.png)
Crafted: ![Screen Shot 2019-11-17 at 8 37 27 PM](https://user-images.githubusercontent.com/52458743/69019026-d9080e80-097c-11ea-888c-6d540ee5075f.png)

Rotary condensentrator: 
Quest: ![Screen Shot 2019-11-17 at 8 38 36 PM](https://user-images.githubusercontent.com/52458743/69019028-dc9b9580-097c-11ea-8939-89f1880becfd.png)
Crafted: ![Screen Shot 2019-11-17 at 8 38 43 PM](https://user-images.githubusercontent.com/52458743/69019030-de655900-097c-11ea-9630-d339133fe4a3.png)

Enrichment chamber:
Quest: ![Screen Shot 2019-11-17 at 8 52 03 PM](https://user-images.githubusercontent.com/52458743/69019031-defdef80-097c-11ea-9d41-d70c468c58f6.png)
Crafted: ![Screen Shot 2019-11-17 at 8 52 10 PM](https://user-images.githubusercontent.com/52458743/69019034-e02f1c80-097c-11ea-9d44-03d62f4dc6b4.png)

Pressurized reaction chamber:
Quest: ![Screen Shot 2019-11-17 at 9 02 48 PM](https://user-images.githubusercontent.com/52458743/69019231-a7dc0e00-097d-11ea-8c66-4c008755663f.png)
Crafted: ![Screen Shot 2019-11-17 at 8 53 05 PM](https://user-images.githubusercontent.com/52458743/69019045-e91fee00-097c-11ea-8ab2-dc66e2dc85cd.png)

Metallurgic infuser: (Quest detected it)
Quest: ![Screen Shot 2019-11-17 at 8 54 00 PM](https://user-images.githubusercontent.com/52458743/69019051-eb824800-097c-11ea-93ed-18822f79f10b.png)
Crafted: ![Screen Shot 2019-11-17 at 8 53 49 PM](https://user-images.githubusercontent.com/52458743/69019047-ea511b00-097c-11ea-9cff-f12219010ee7.png)

**Comment by oly2o6** [comment]
I will sort 5is, if you need the quest completing let me know
