### ISSUE TITLE
New prep #171 has wrong amount of ingots

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#113]
Since you need 104 fusion casings in total (98 casings in the structure, + 6 to make 3 cores), you actually need 104 tungsten and 104 neodymium ingots, not 100.
![Screen Shot 2019-11-17 at 9 09 56 PM](https://user-images.githubusercontent.com/52458743/69019442-aeb75080-097e-11ea-95e1-c5528a5071eb.png)
![Screen Shot 2019-11-17 at 9 10 17 PM](https://user-images.githubusercontent.com/52458743/69019443-af4fe700-097e-11ea-8d88-0b456762eac9.png)

**Comment by oly2o6** [comment]
Welllll, I was close lol I’ll fix this
