### ISSUE TITLE
Mana Spreader Also Gated behind Machine Block

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#12]
Need Washed Gold ore. to make the mana spreader? 

## Expected Behavior
Shouldnt be gated behind something that needs it ?

## Current Behavior
Is gated behind something that needs managlass cant make it without a spreader.

## Possible Solution
Change the machine block recipe OR change the spreader recipe to an attainable option such as pulverizer which is available at this point. As well as steam dynamo for power. Changing all the recipe's to thermal recipes would gate the other stuff behind thermal but idk if thermal should be available already?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by oly2o6** [comment]
Working on a fix will be implemented next update
