### ISSUE TITLE
[BQM] Quest: It's living

### ISSUE THREAD

**Issue by mtimyself** [AllTheMods/ATM3-Expert#120]
When picking up living wood for the first time it completes two quests. One is in the book "Wood you risk it?" but it also completes an invisible quest called "It's living" (or something like that, nearly missed it).
Same for the living rock quest. It has a duplicate, invisible quest that completes.

**Comment by oly2o6** [comment]
Odd...

**Comment by mtimyself** [comment]
I have found similar issues with "invisible" quests.
https://github.com/AllTheMods/ATM3-Expert/issues/123
https://github.com/AllTheMods/ATM3-Expert/issues/124
