### ISSUE TITLE
[BQM] Quest: Hardened upgrade kit

### ISSUE THREAD

**Issue by mtimyself** [AllTheMods/ATM3-Expert#122]
The quest text for "Hardened upgrade kit" refers to the fact that Nickel has to be obtained in the nether.
However, Nickel can be found at any height in the Overworld.

**Comment by oly2o6** [comment]
note for crayon: change the description of this quest to be jargon about how adding the upgrade kit to the dynamo would allow the boiler conversion to be added which allows for double rf output
