### ISSUE TITLE
mining level issues

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#135]
Manasteel mining level:
- Knightslime can be obtained as soon as you get a smeltery
- Invar can be obtained as soon as you get a smeltery
- Signalum can be obtained as soon as you get a smeltery
- Amber can be mined from Amber-Bearing Stone
- Survivalist's Pickaxe from Forestry can be obtained as soon as you get a smeltery (bronze ingots)

***A few, if not all, of BoP ores have manasteel-mining level. They don't spawn on the server because BoP isn't enabled but it might break progression if they spawn in a BoP-enabled world.

Steel mining level:
- Evil Infused ingots can be obtained as soon as you go to the nether (the gate is the nether star required for the ingots)
- The sentient pickaxe can be obtained in the very beginning of blood magic
- This one is kind of a reach: the bound pickaxe can be obtained without getting steel, although it would IMO take as much/if not more/work (a T3 altar and a decent amount of time spent killing mobs to get will)

*** Amethyst from BoP has steel mining level. Again it doesn't spawn on the server but idk if it would spawn in a BoP enabled world.

MACHINES/GADGETS
The block breaker from randomthings and openblocks and the conversion wand from Astral Sorcery don't break progression.

- The auto-breaker from Actually Additions can mine steel mining level blocks, so it breaks progression.
- The Block Breaker from Industrial Foregoing can mine steel mining level blocks, so it breaks progression.
- The exchanging gadget can mine steel mining level blocks, so it breaks progression.
- The mechanical miner from ExU2 can mine manasteel mining level blocks, so it slightly breaks progression. It doesn't drop steel mining level blocks though.

**Comment by TheGoldCrayon** [comment]
Just a couple of questions about the machines/gadgets. Do you need steel at all to make any of those four things? I'm guessing not, save for *maybe* IF's block breaker, but I just want to be sure.

**Comment by bomber12309** [comment]
None of them do, the AA breaker gate is an atomic reconstructor, IF is an empowerer, the exchanging gadget is diamonds, mechanical miner is iron/redstone.

**Comment by TheGoldCrayon** [comment]
fixed
