### ISSUE TITLE
creative items issues

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#136]
The creative fluid tank from Mekanism, the Tinkers' creative modifiers and the Creative Conversion Kit from Thermal can use ANY item with the atmtweaks:item_material item id (which is every ATM Tweaks item). 

Also, the creative tank recipe from Mek crafts into a basic fluid tank instead of the creative one.
![Screen Shot 2019-11-24 at 11 45 38 AM](https://user-images.githubusercontent.com/52458743/69497926-10604900-0eb0-11ea-9afb-df0deab0214b.png)
![Screen Shot 2019-11-24 at 11 45 54 AM](https://user-images.githubusercontent.com/52458743/69497925-10604900-0eb0-11ea-93cf-d4eb29d38c69.png)
![Screen Shot 2019-11-24 at 11 46 58 AM](https://user-images.githubusercontent.com/52458743/69497936-25d57300-0eb0-11ea-9de3-63b852464ecd.png)

**Comment by oly2o6** [comment]
ohh wtf lol better get that fixed
