### ISSUE TITLE
remove second item IO circuit board recipe

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#137]
for some reason, there's a precision assembler recipe that uses literally 1 redstone and nothing else. there's plenty of precision assembler recipes that require redstone dust, so it makes all those recipes impossible.
![Screen Shot 2019-11-24 at 6 00 10 PM](https://user-images.githubusercontent.com/52458743/69503102-72d33c80-0ee4-11ea-9908-68be39bf238f.png)

**Comment by oly2o6** [comment]
weird, i didnt add that recipe

**Comment by oly2o6** [comment]
possibly fixed. will check tomorrow before the dev server update
