### ISSUE TITLE
void siphon requires the wrong research

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#139]
got the void siphon entry completed but it still says "missing research"

![Screen Shot 2019-11-24 at 9 07 30 PM](https://user-images.githubusercontent.com/52458743/69506898-9d31f380-0efe-11ea-848a-fe10e2e312ed.png)
![Screen Shot 2019-11-24 at 9 07 43 PM](https://user-images.githubusercontent.com/52458743/69506899-9d31f380-0efe-11ea-9618-59e952f3e6ec.png)

**Comment by oly2o6** [comment]
maybe fixed in next update so check that out for me if you get the chance
