### ISSUE TITLE
Unfired Clay Bucket Cannot be Fired/Smealted in Kiln

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#14]
Clay balls when placed in Kiln make bricks which can only be used to make a flower pot. Using three clay balls you can craft an unfired clay bucket, but it can not be Fired in a Kiln. This seems counter-intuitive and should be allowed.

Allowing a clay bucket to be smealted in a kiln would allow a player, possibly, to get lava for a smealtry and use that to create ingots for other recipes.

**Comment by SpeedSlider** [comment]
Additional consideration for the kiln might be flour by NuclearCraft as a good early game source of food when combined with an AE2 quartz grinder.

**Comment by oly2o6** [comment]
Already fixed, flour from NC and also rice bread will be added to kiln

**Comment by drizzs** [comment]
by the time you need a bucket you should have a furnace already, so you dont need to fire a clay bucket in a kiln. Just saying!
