### ISSUE TITLE
disable electrical and nuclear engineer trades

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#140]
the Electrical Engineer and Nuclear Engineer villagers from IC2C have some pretty OP and/or progression-breaking trades.
i'm not sure if they can be found naturally, but they can be spawned from a spawner.

![Screen Shot 2019-11-26 at 3 55 53 PM](https://user-images.githubusercontent.com/52458743/69672148-793cf200-1065-11ea-8612-05400f6353fa.png)
![Screen Shot 2019-11-26 at 3 56 01 PM](https://user-images.githubusercontent.com/52458743/69672150-793cf200-1065-11ea-9154-7580f374e09a.png)
![Screen Shot 2019-11-26 at 3 57 16 PM](https://user-images.githubusercontent.com/52458743/69672173-86f27780-1065-11ea-90e9-1ab1ee220a95.png)
(can be broken for an adv. machine frame)

**Comment by Trinsdar** [comment]
Yah you'll have to completely disable the villagers in the config, though that will only disable the trades, the villagers will still spawn but be as useless as nitwits

**Comment by TheGoldCrayon** [comment]
should be fixed in the most recent update. (1.2.0)
