### ISSUE TITLE
can still get NC manganese through alchemistry

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#142]
i don't think it's intended because the manganese ingot recipe was disabled.
you can still craft manganese (the element) into manganese dust with the alchemical combiner, as well as liquify the element for liquid manganese

![Screen Shot 2019-11-28 at 5 27 51 PM](https://user-images.githubusercontent.com/52458743/69833848-72001a80-1204-11ea-8432-02cdc93bd368.png)
![Screen Shot 2019-11-28 at 5 27 42 PM](https://user-images.githubusercontent.com/52458743/69833849-7298b100-1204-11ea-833e-dbfe69b25362.png)

**Comment by TheGoldCrayon** [comment]
fixed
