### ISSUE TITLE
add Machine Case recipe to combination crafting

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#144]
Once you get combination crafting, the only uses for the empowerer are empowered canola (extremely optional and usually requires a dedicated empowerer setup anyways) and the machine case. Combination crafting requires the display stands, and having such a big setup just to create machine cases is kind of absurd, which is why I think you should be able to craft machine cases w/ the crafting core.

**Comment by TheGoldCrayon** [comment]
added in upcoming update
