### ISSUE TITLE
Empowered Emeradic Block uses little RF/t in comb. crafting

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#145]
All empowered blocks take 7.5 or 10 ticks to empower in combination crafting, but emeradic blocks take 666.7 ticks
![Screen Shot 2019-11-28 at 6 49 53 PM](https://user-images.githubusercontent.com/52458743/69835462-eab8a400-120f-11ea-8afa-d24f136f31d5.png)
![Screen Shot 2019-11-28 at 6 50 03 PM](https://user-images.githubusercontent.com/52458743/69835463-eab8a400-120f-11ea-8279-8fb1619943ed.png)

**Comment by oly2o6** [comment]
missed a 0

**Comment by bomber12309** [comment]
think you added an extra one to every other block too, they're all 100x the RF/t of normal crystals (id expect it to be only 10x)
