### ISSUE TITLE
[BUG] Impossible to create Tinker's Clear Glass

### ISSUE THREAD

**Issue by tjsd** [AllTheMods/ATM3-Expert#148]
V1.0
I can smelt sand but it is impossible to pour it into a basin from the smeltery.
The tinker's clear glass is required to make the IC2 machine frame.

## Expected Behavior
When I right click I expect to see liquid glass flowing from the faucet into the basin, but it plays a super short animation, shows some liquid is in the basin but there is nothing there. The controller still shows 1 block of liquid glass.

## Steps to Reproduce
1. Get smeltery
2. Melt sand into glass
3. Right click faucet above basin
4. be dissapointed

**Comment by TheGoldCrayon** [comment]
Hi! Can you do me a couple favors? First, make sure you are using sand and no compressed sand, as that melts into vitrified sand. Second, are you using the porcelain setup or a full blown TiCon smeltery? Finally, if you would be able to take a screenshot of your basin/drain, and the contents of your smeltery, that would be wonderful.

**Comment by tjsd** [comment]
Hey!
Yes its sand. here is the result in ticon smeltery
![image](https://user-images.githubusercontent.com/7138125/69905229-e677bc80-13b0-11ea-98c3-9f31a3e058dc.png)
This is the smeltery:
![image](https://user-images.githubusercontent.com/7138125/69905240-08713f00-13b1-11ea-8683-fb79636db3e8.png)
After right clicking the faucet I get a "small squirt" of glass.
![image](https://user-images.githubusercontent.com/7138125/69905245-1fb02c80-13b1-11ea-9211-221dab90b04f.png)
But the controller still shows full.

**Comment by tjsd** [comment]
A restart of the server solved it for me

**Comment by oly2o6** [comment]
I think there may have been a problem with  a slight corruption of the server files (FULL) try getting the server owner to replace the /scripts folder with the ones to match the client until tomorrow when I’m doing an update

**Comment by oly2o6** [comment]
Fixed in 1.0.1
