### ISSUE TITLE
World Generation seems to bring server down to a halt when generating chunks

### ISSUE THREAD

**Issue by ixanza** [AllTheMods/ATM3-Expert#151]
While generating chunks while exploring, the world gets slower and slower until the server stops. This is on a dedicated server that handles ATM3:R fine so I'm not sure why it's crashing here

## Expected Behavior
World should generate fine

## Current Behavior
World slowly loses TPS until server closes

## Steps to Reproduce
1. Explore a really busy biome like Jungle for me 
2. Keep exploring as TPS drops
3. Server closes due to time per tick being more than 60

## Log
Crash Log : https://gist.github.com/ixanza/a834c527d8c40b95dab8a1678f10991f
Latest Log before crash : https://gist.github.com/ixanza/613d3c0759f2863472fb3ed5a3e3c9f6

**Comment by oly2o6** [comment]
Are you using sponge? I’ve heard of this only with sponge so far but I know someone with a fix

**Comment by ixanza** [comment]
No this is purely forge sadly
