### ISSUE TITLE
empowered enori block uses empowered enori crystal

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#152]
it should be using enori blocks to make empowered enori blocks, but it uses enori crystals to make empowered enori blocks instead.
![Screen Shot 2019-12-01 at 1 28 43 PM](https://user-images.githubusercontent.com/52458743/69918349-cee71500-143e-11ea-8656-036348744a28.png)

**Comment by oly2o6** [comment]
Fixed in next update
