### ISSUE TITLE
No cover facades for logistic pipes (Recommendation)

### ISSUE THREAD

**Issue by dmb1881** [AllTheMods/ATM3-Expert#154]
- For Logistic Pipes, there are no cover facades to cover pipes.

Logistic Pipes is partially dependent on Buildcraft for some of its items. 

I suggest adding buildcraft

Adding buildcraft would allow for usage of covers for pipes.

**Comment by TheGoldCrayon** [comment]
While it's possible it might get added, therw ould have to be either a lot of gating or disabling of stuff from the mod to match progression. And imo, disabling most of a mod just so you can use a couple features of it wouldn't be worth it.

**Comment by dmb1881** [comment]
I do agree, it would seem pointless if we didn't gate it for a few features. My suggestion would be to make it similar to how FTB Infinity Evolved combined the two together. Forcing you to use buildcraft lasers to make chipsets and etc. Would be neat imo.

**Comment by dmb1881** [comment]
Nevermind on adding buildcraft, you can't even attach facades/plugs to the pipes anymore.
