### ISSUE TITLE
Logistic Pipes no crafting Recipe for ALL Power Suppliers.

### ISSUE THREAD

**Issue by dmb1881** [AllTheMods/ATM3-Expert#155]
## Expected Behavior
Expected crafting recipe for all Power Suppliers from Logistic Pipes.

## Current Behavior
No recipe appears in JEI (Maybe visual, may not be a crafting recipe?)

## Possible Solution
Add a crafting recipe for Power Suppliers

## Steps to Reproduce
Press R on any of the Power Suppliers.

## Detailed Description
Not sure of a good balanced way to request this so my idea would be to make it like the power transporter but replace the middle chipset with the approriate cable.
This is what I would make the recipies: (I hovered over the item it was supposed to craft, also the top piece being a power transportation upgrade)

Leadstone Energy Duct
![2019-12-02_23 10 50](https://user-images.githubusercontent.com/10456033/70020083-912adf00-1559-11ea-86ec-7849ae139cd9.png)
Copper Insulated Wire
![2019-12-02_23 11 06](https://user-images.githubusercontent.com/10456033/70020084-912adf00-1559-11ea-8e60-d79aa49e90fc.png)
Gold Insulated Wire
![2019-12-02_23 12 08](https://user-images.githubusercontent.com/10456033/70020085-912adf00-1559-11ea-8c8d-282cc21eece9.png)
HV Insulated Wire
![2019-12-02_23 12 19](https://user-images.githubusercontent.com/10456033/70020086-912adf00-1559-11ea-810a-43711c8f4223.png)

Image of what it is supposed to look like working:
![2019-12-02_22 51 59](https://user-images.githubusercontent.com/10456033/70020175-dc44f200-1559-11ea-9c5f-d83dee2f5358.png)

**Comment by Sleeeper** [comment]
Power suppliers aren't finished when porting to 1.12.2 version so dev's made them uncraftable.
Same with others stuff that's uncraftable

**Comment by dmb1881** [comment]
Gotcha, wasn't sure if it was on accident or if the devs did it. Although it does seem that it is working. (At least from my tests) must be an issue with them or something that I just don't know about. Or just no crafting recipe.

**Comment by oly2o6** [comment]
The logistics book will help when figuring o what is there and what isn’t I’ll close this but keep everyone updated if logistics pipes gets any updates on this
