### ISSUE TITLE
Recipe Bug: Flint n steel

### ISSUE THREAD

**Issue by tjsd** [AllTheMods/ATM3-Expert#156]
v1.0.1

Just a quick note, in progression you make us get a compressor and carbon to get to the nether for flint'n steel . I guess you wanted us to have a different recipe for that.
But it only requires a piece of flint and a piece of iron.
From the progression I think it is supposed to be a manasteel with a carbon plate to make it?

**Comment by dmb1881** [comment]
I think the purpose for carbon being as part of the quest so that you couldn't skip the stage without making the compressor. But that's just my guess.

**Comment by TheGoldCrayon** [comment]
The way it's set up right now isn't how it's fully meant to be. The Nether was intended to be gated behind manasteel for obsidian and flint and steel for fire, for which the recipe needed the carbon plate. However, you can't mine anything in the nether without a manasteel level tool, so needing the flint and steel gated wasn't necessary. We're still in the process of trying to figure out how to make this work using carbon plates but still following gating

**Comment by dmb1881** [comment]
Perhaps make it require manasteel and carbon to make the recipe. Also it's kind of hard to gate the nether portal considering there are multiple ways to get there with the fling and steel.

**Comment by tjsd** [comment]
Yes, you can light the portal with charges and burning wood with lava. But then the quest netherportal should not be dependant on the other steps there. Also I completly skipped all that with finding mantasteel in dungeon loot and made it when I got the smeltery.

**Comment by oly2o6** [comment]
We are working on the flint and steel and nether portal of the quest line right now we just don’t know which way we should do it

**Comment by TheGoldCrayon** [comment]
recipes for flint and steel and fire charges have been changed, along with various additions to make a smoother path through this.
