### ISSUE TITLE
Add MCMultipart mod for Logistic Pipes Covers

### ISSUE THREAD

**Issue by dmb1881** [AllTheMods/ATM3-Expert#157]
Logistic Pipes and Chisel and bits are both dependent on McMultiPart, my suggestion is to add MCMultipart to the pack.

**Comment by dmb1881** [comment]
Here's Proof, showing MCMultiPart working.
![2019-12-03_17 45 23](https://user-images.githubusercontent.com/10456033/70096314-c9333000-15f4-11ea-9ca2-840f28cbad05.png)

**Comment by TheGoldCrayon** [comment]
mod added
