### ISSUE TITLE
remove second control circuit board recipe

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#158]
#137 was fixed but now there's the exact same issue with the control circuit board instead of item IO circuit

![Screen Shot 2019-12-03 at 5 24 57 PM](https://user-images.githubusercontent.com/52458743/70095102-eca8ab80-15f1-11ea-94a0-4498e1b2fd7e.png)

**Comment by Trinsdar** [comment]
Did this exist before the fix?

**Comment by bomber12309** [comment]
I don't think so, I went through the recipes a couple of times but never noticed it until the IO item boards were fixed

**Comment by Trinsdar** [comment]
Figures. I say we should just make our own multiblock for this if it keeps happening

**Comment by oly2o6** [comment]
Every time I remove one a new one pops up

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0
