### ISSUE TITLE
bee receptacle still has original recipe

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#159]
should only be the recipe that uses industrium
![Screen Shot 2019-12-03 at 10 08 52 PM](https://user-images.githubusercontent.com/52458743/70110243-6786bc00-161c-11ea-9a8e-3e0617d7d742.png)

**Comment by PrototypeTrousers** [comment]
extract the config file from the gendustry jar (gendustry-1.6.5.8-mc1.12.2.jar\assets\gendustry\config\recipes.cfg) into the minecraft\config\gendustry\overrides folder, then comment lines 45,46,47.

**Comment by TheGoldCrayon** [comment]
fixed in upcoming update. Thanks for the help prototype
