### ISSUE TITLE
Questbook Issues

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#16]
Oly said they were fixed but just incase this hasnt been fixed I'll post a screenshot but With how you need mana before you make a compressor, the quest book says you make a compressor then make a mana pool, but why fork it both ways if you're gated behind a compressor anyways? I'm not sure. The book is all over the place.

## Expected Behavior
It should be, Munchdew -> Spreader --> Pool -->Machine Block --> Machines.

## Current Behavior

![image](https://user-images.githubusercontent.com/51287780/59078483-55b29f00-88ad-11e9-8427-c45fbb2af9ba.png)

## Possible Solution
Change the book!

**Comment by oly2o6** [comment]
Alllllll fixed in today’s update don’t worry about itttt lol
