### ISSUE TITLE
overloaded recipes

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#160]
Overloaded's infinity capacitor, barrel and fluid thingy have the vanilla recipes, which means you can get infinite power, fluid and item (who cares about that one) storage as early as you get to the nether.
I suggest using the ATM star for the Power Core (or slightly behind it, since you can use the atm star for infinite power generation). Fluids and items don't matter as much, but they still should be gated later in the game.

**Comment by TheGoldCrayon** [comment]
removed mod
