### ISSUE TITLE
There is a calculation error when converting EU to Joules and back.

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM3-Expert#161]
Build something like this:
https://imgur.com/a/DGu9EmA

There is a calculation error when converting EU to Joules and back, using mekanism cables.

## Expected Behavior
Stored energy not changing at all.

## Current Behavior
Stored energy increased.

## Possible Solution
Solution not found.

## Steps to Reproduce
See image above.

## Log
N/A

## Detailed Description
Since the EuToJoules config is changed by this pack I don't know if it's a mekanism bug or just wrong config.

**Comment by oly2o6** [comment]
This is a mod issue with ic2 classic, might be intended might not but as far as I know the only conversion is basic universal cables, others don’t work and even so I reduced the rates so doing that would actually use EU (kindof a diminisher for people trying to do cheaty eu conversion)

**Comment by ghost** [comment]
> 
> 
> This is a mod issue with ic2 classic, might be intended might not but as far as I know the only conversion is basic universal cables, others don’t work and even so I reduced the rates so doing that would actually use EU (kindof a diminisher for people trying to do cheaty eu conversion)

It didn't use EU but "creates" more EU instead.

**Comment by oly2o6** [comment]
Ohh...
