### ISSUE TITLE
Using Carryon, on Logistic Pipes causes Entity Errors.

### ISSUE THREAD

**Issue by dmb1881** [AllTheMods/ATM3-Expert#162]
Using carryon on LP causes Entity errors, causing players to crash trying to break the block.

## Expected Behavior
Should be able to break the block.

## Current Behavior
Trying to break the block causes the player to crash.

## Possible Solution
Remove Logistic Pipes from carryon list.

## Steps to Reproduce
1. Place LP Compiler
2. Use Carryon to pick it up
3. Place it back down
4. Try to break Compiler.

**Comment by Sleeeper** [comment]
Same with power junction and others,
plz add LP mod to carryon blacklist.

As a workaround, a player can use cardboard box on bugged block and then break and trash it.

**Comment by TheGoldCrayon** [comment]
LP blacklisted
