### ISSUE TITLE
weird mining textures

### ISSUE THREAD

**Issue by sossololpipi** [AllTheMods/ATM3-Expert#163]
## Expected Behavior

normal mining animation

## Current Behavior

crafting tables and other random furniture appear instead

## Possible Solution

some mod causing this bug

## Steps to Reproduce

1.log in world
2.break a block
3.???
4.profit

**Comment by oly2o6** [comment]
This is being worked on, we have to make a new mod to replace another one then redo the recipes so it should be with you guys for 1.0.3 next week either on Friday or before it
