### ISSUE TITLE
unable to use totemist drum in selector mode

### ISSUE THREAD

**Issue by sossololpipi** [AllTheMods/ATM3-Expert#166]
## Expected Behavior

totemist drum should make a noise and have sparkles around it

## Current Behavior

player picks the thing up

## Possible Solution

changing the Carry On config

## Steps to Reproduce

1.make totemist drum
2.shift right click drum with an empty hand

## Detailed Description

totemic:drum is the block you're looking for

**Comment by oly2o6** [comment]
Temp fix, try standing further back so carryon doesn’t work

**Comment by oly2o6** [comment]
But yeah I’ll get this done

**Comment by dmb1881** [comment]
You can change the keybind for carryon in the controls menu so it won't be shift to pick up.

**Comment by TheGoldCrayon** [comment]
totemic blacklisted in carryon in upcoming update
