### ISSUE TITLE
With the removal of the crafting hammer / its recipe, metal bender presses are no longer legitimately obtainable

### ISSUE THREAD

**Issue by DestructivForce** [AllTheMods/ATM3-Expert#169]
## Expected Behavior
Metal bender presses have altered recipes so the metal bender is still functional.

## Current Behavior
The crafting hammer's recipe is disabled, and the blank press and rolling press both require it to craft them. Due to their inclusion in the new potentials tier 1 quest, it is assumed that they are still meant to be obtainable.
![2019-12-06_21 12 44](https://user-images.githubusercontent.com/50807043/70368200-88921b80-186d-11ea-9abb-02d330e69244.png)

## Possible Solution
Either revert the removal of the crafting hammer's recipe or provide an alternative recipe to craft the presses.

**Comment by oly2o6** [comment]
Bug fix version incoming
