### ISSUE TITLE
Ingots are still found in loot chests

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#17]
Currently working with the 1.2.0 Alpha pack in single player. Came across a village that was not previously found and got the following ingots. Iron, copper, dark steel, vibrant alloy, electrical steel, and pulsating iron. Immersive engineering building also had aluminum ingots. I also found iron boots, chest plate, and an iron pick.

**Comment by FallenEagle1** [comment]
To add to it, seems like something is up with loot tables, as this line shows up a bunch: `[Server thread/WARN] [minecraft/LootTable]: Tried to over-fill a container`

**Comment by SpeedSlider** [comment]
Also, gold ingots can be found and used to make permenant tinkers casts instead of temporary molten clay ones for early game.

**Comment by oly2o6** [comment]
Blue 8s working on world gen and loot tables
