### ISSUE TITLE
[BUG] Cheap Advanced Machine Blocks by Breaking IC2 Metal Bender

### ISSUE THREAD

**Issue by Mr-Rixa** [AllTheMods/ATM3-Expert#170]
## Expected Behavior

Metal Bender breaks into a **Machine Block**

## Current Behavior

Metal Bender breaks into a **Advanced Machine Block**

## Steps to Reproduce

1. Place down a IC2 Metal Bender
2. Break it with a pickaxe
3. Pick up advanced machine block
4. ???
5. Profit

**Comment by phantamanta44** [comment]
isn't this intended behaviour in ic2? you usually need a wrench to dismantle machines

**Comment by Mr-Rixa** [comment]
Yes it indeed is intended mechanics of ic2, BUT making Metal Bender in this pack doesn't require any advanced machine blocks, it's a "tier 1" machine. In this pack you need steel to make advanced machine blocks and you get to steel on "tier 3".

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0
