### ISSUE TITLE
Pack currently not playable due to incorrect Kiln recipes [v1.1.1]

### ISSUE THREAD

**Issue by Boomflex** [AllTheMods/ATM3-Expert#171]
Kiln currently not making Unfired Barrels in to White Porcelain Barrels and also it doesn't make the Faucets either so currently stuck...

Any ETA on a bugfix for this?

**Comment by oly2o6** [comment]
“ Due to a bug in Atum when adding a new crafttweaker recipe to the kiln it will remove some of the others randomly, going to speak to the author but for now go to a village and get a furnace through world gen” taken from another issue report about the kiln

**Comment by TheGoldCrayon** [comment]
This has been fixed in current update, and the quesbook will be updated to reflect this change in the next update.
