### ISSUE TITLE
Mek steel dust in an Energized Smelter makes mek steel ingots

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#173]
The recipe should output thermal foundation steel and according to JEI, it does. But putting steel dust from mekanism into an energized smelter or smelting factory makes mekanism steel ingots instead. However, making it in a non-mek furnace seems to work correctly.

I'm not sure if this can be fixed since it should already be working, however changing the Metallurgic Infuser's output (enriched iron -> steel dust) to Thermal Foundation's steel blend should work. The steel blend smelts correctly in the mek energized smelter.

![Screen Shot 2019-12-08 at 1 40 21 PM](https://user-images.githubusercontent.com/52458743/70394175-56450300-19c0-11ea-825a-660dbff6a84d.png)
![Screen Shot 2019-12-08 at 1 40 06 PM](https://user-images.githubusercontent.com/52458743/70394176-56dd9980-19c0-11ea-9c8d-5f647922bb0f.png)

**Comment by TheGoldCrayon** [comment]
fixed in upcoming update. infuser now give steel blend from thermal
