### ISSUE TITLE
Cyclic is listed in the modlist but isn't in the modpack

### ISSUE THREAD

**Issue by ignatremizov** [AllTheMods/ATM3-Expert#174]
## Expected Behavior
Cyclic is a very useful mod in many aspects of the game. I agree with having it in the modpack, and is listed in the modlist, so I had expected it to download.

## Current Behavior
Cyclic is not in the modpack. I downloaded the .zip from curseforge.

## Detailed Description
Is this intentional or accidental?

**Comment by oly2o6** [comment]
The modlist on github is out of date I might be adding cyclic back in the future
