### ISSUE TITLE
Terraformer from EU2 uncraftable

### ISSUE THREAD

**Issue by Salnex** [AllTheMods/ATM3-Expert#177]
Extra Utilities Terraformer uses EU2's machine base to craft, as such is not craftable. It doesn't seem intentional as other things that would normally use the machine base have had their recipes changed, or straight up removed.

## Expected Behavior
The item has a recipe that is craftable, or no recipe

## Current Behavior
The item is uncraftable

## Possible Solution
The recipe is changed to something of an appropriate cost, or the recipe is removed entirely to make it clear that the lack of inclusion is intentional

**Comment by TheGoldCrayon** [comment]
climagraph blocks now craftable in upcoming update
