### ISSUE TITLE
Nether Portal Not Teleport!

### ISSUE THREAD

**Issue by lucasdoniytb** [AllTheMods/ATM3-Expert#179]
## Possible Solution
 Remove a NetherPortalFix Mod

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tjsd** [comment]
Nether is restricted by gamestages, you HAVE To complete the questline to be allowed to enter the nether.

**Comment by lucasdoniytb** [comment]
Yes!

**Comment by lucasdoniytb** [comment]
I discovered the problem. It was the gamestages that had reset :/
