### ISSUE TITLE
Kiln no longer smealts unfired porcelain balls.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#18]
Kiln issue with unfired barrels has been resolved but now the kiln will not smealt unfired porcelain balls. JEI shows you need a furnace to do it. So the last update (1.2.0) appears to have swapped unfired barrels and unfired porcelain balls.

**Comment by oly2o6** [comment]
That’s amazingly stupid I’ll get it fixed
