### ISSUE TITLE
GAME STAGE RESET

### ISSUE THREAD

**Issue by sreekrishna5** [AllTheMods/ATM3-Expert#180]
## Current Behavior

Every time the whole  modpack is relaunched the gamestages get reset

## Possible Solution

running the appropriate cmd provided in the quest book after launch

## Steps to Reproduce

1.
2.
3.
4.

**Comment by galori** [comment]
My quests reset too

**Comment by Rixxaw** [comment]
Yeah unable to go "Back" to the nether, had to go into creative and gamestage /add @p nether.  All my quests appear to be completed as per normal.

**Comment by TheGoldCrayon** [comment]
1) What do you use for launching the pack, twitch or multimc?
2) Do you play on a server or solo?
3) Did you copy over any files/folders from your previous update to the current one?

**Comment by sreekrishna5** [comment]
1.Twitch launcher
2.Single Player
3. No

**Comment by TheGoldCrayon** [comment]
Will look into this, but not 100% sure what I can do. I didn't do anything with gamestages nor do I know how they fully work.

**Comment by sreekrishna5** [comment]
ohh and also if i hav a home set in an unlock place like the nether i can still teleport to it juz the portal is not working for me

**Comment by sreekrishna5** [comment]
It is now working and fixed in the latest version
