### ISSUE TITLE
Quests got reset when upgrading from 1.0.1 to 1.1.1.

### ISSUE THREAD

**Issue by galori** [AllTheMods/ATM3-Expert#181]
## Current Behavior

All of the quests are marked as not complete

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

I was 1 quest from being done with Tier 1 and now its showing all of it as not complete.

**Comment by sreekrishna5** [comment]
That was because new quest were added and some things were gated through game stages

the quests tht u already completed will be marked completed

**Comment by oly2o6** [comment]
You should only have to complete a few quests that had added items into them
