### ISSUE TITLE
Crafting any recipe with ingredients stack size greater than 1 inside RFTools Storage Scanner's crafting grid will dupe those ingredients

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM3-Expert#182]
Tested with ic2 30k coolant cell.
Need to use JEI to fill the recipe otherwise it won't craft.

## Expected Behavior
Consumes all ingredients needed.

## Current Behavior
Multiple stacks of ingredients get created out of thin air.

## Possible Solution
N/A

## Steps to Reproduce
1. Place down a Storage Scanner and connect it to RF power.
2. Get 12 tin ingots and 6 water cells.
3. Open Storage Scanner GUI and use JEI to fill its crafting grid with 30k coolant cell recipe which uses those ingredients.
4. Click "Craft one".

## Log
N/A

## Detailed Description
It seems like having more than enough items (in this case more than 12 tin ingots or 6 water cells) in your inventory causes it to dupe even more. And the recipe is not craftable in a normal crafting table.

**Comment by Rixxaw** [comment]
I couldn't get it to craft at all for me actually I had to give up on IC2 ... Didn't realize it was just the RFTools system.  It doesn't like having double stack items in the crafting grid.
