### ISSUE TITLE
can't craft/smelt/fire Unfires Porcelain Barrel

### ISSUE THREAD

**Issue by emilyvans** [AllTheMods/ATM3-Expert#184]
## Expected Behavior

that you can smelt a Unfires Porcelain Barrel

## Current Behavior

there is no way to optain porcelain barrel(to smelt Unfires Porcelain Barrel can only been done with furnace or higher)

## Possible Solution

to make it smeltable by the kiln

## Steps to Reproduce

try to make  a porcelain barrel

## Detailed Description

not needed

**Comment by emilyvans** [comment]
porcelain Faucets same

**Comment by TheGoldCrayon** [comment]
fixed in an upcoming update
