### ISSUE TITLE
Forged Industrium isn't crafting

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#185]
The recipe seems fine, I can place it with JEI, however it won't craft the forged industrium.

![Screen Shot 2019-12-15 at 3 07 42 PM](https://user-images.githubusercontent.com/52458743/70868243-c1f11800-1f4c-11ea-880e-20ab17cf3535.png)

![Screen Shot 2019-12-15 at 3 07 50 PM](https://user-images.githubusercontent.com/52458743/70868242-c1588180-1f4c-11ea-9f88-0cead3fd64bd.png)

**Comment by TheGoldCrayon** [comment]
fixed in upcoming update. blank spots are supposed to be dilithium crystals. issue was in the recipe, the item name was misspelled.
