### ISSUE TITLE
Certain creative items don't give the ATM star back

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#186]
All the creative items have a tooltip saying it doesn't consume the ATM star, but they consume the ATM star and give back an orb of transcendance, I'm guessing it's just a metadata issue

This affects: the creatie jetpack, creative flux pack, creative fluxbore, creative fluxsaw, creative fluxomagnet, mek's creative energy, mek's creative fluid, bibliocraft's oak creative bookcase, rftools' creative powercell and Applied Energistics' creative energy cell.

**Comment by TheGoldCrayon** [comment]
will be looked into and *hopefully* fixed on next update

**Comment by TheGoldCrayon** [comment]
fixed in upcoming update
