### ISSUE TITLE
[v1.2.1] [EnderIO] Upgrade Dupe Bug

### ISSUE THREAD

**Issue by mtimyself** [AllTheMods/ATM3-Expert#188]
Equipping an armor item via right click will dupe the upgrades inside by retaining them in the armor and also placing them in the player inventory.

**Comment by TheGoldCrayon** [comment]
Pretty sure this is an ender io bug, and not a modpack bug. without disabling the armor, there's not much we can do

**Comment by PABessero** [comment]
It's will apparently be fixed in the next version of EnderIO, i know the linked one is a duplicate but i cant find the original one
https://github.com/SleepyTrousers/EnderIO/issues/5292
