### ISSUE TITLE
[Mod Request] Super Sound Muffler

### ISSUE THREAD

**Issue by mtimyself** [AllTheMods/ATM3-Expert#189]
Small little utility mod.
No impact on progression.

https://www.curseforge.com/minecraft/mc-mods/super-sound-muffler

**Comment by PABessero** [comment]
https://github.com/AllTheMods/ATM-4/issues/1

**Comment by TheGoldCrayon** [comment]
Will look into adding this into next update. 
Also Pab, not sure what you're trying to refer to there.

**Comment by PABessero** [comment]
Yeah i miss clicked i wanted to scrap the message and ended up sending it instead

**Comment by TheGoldCrayon** [comment]
added in  upcoming update
