### ISSUE TITLE
Ore Unification

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#19]
Multiple versions of ores are still found in the world. Ore unification should be performed to prevent inventory overload and ore usage issues.

**Comment by SpeedSlider** [comment]
Lead ore by Nuclear craft is harvestable with a flint pickaxe. Lead ore by thermalcraft is bronze level and not harvestable by a flint pickaxe.

**Comment by TheGoldCrayon** [comment]
To add on to this, I've noticed libvulpes copper and tin ores, as well as nuclearcraft tin, copper, and lead ores

**Comment by oly2o6** [comment]
Fixed
