### ISSUE TITLE
ATM3-Expert conflict with Proxys 

### ISSUE THREAD

**Issue by 123Kappa** [AllTheMods/ATM3-Expert#190]
## Current Behaviour
We have a moded network and we have encountered packet errors caused by JustEnoughIds recent extended enchantment and potion packet ID changes. 

This error occurs when a player has a potion effect, even vanilla ones. 
When that happens all the players inside the server get kicked. 

##  Solution
Downgrading JustEnoughIds  1.0.1-16 version and adding JustEnoughIDs Integration (JEIDsI) to the client. 
In 1.0.1-16 this issue does not occur. 
The client needs JEIDsI which an addon mod that fixes some of that version's issues. 
That mod was later merged with JEID in a future version.

This issue first appeared on Stoneblock 1 and the author had to downgrade. 
You can view more information in the below links. 

## Steps to Reproduce

1. Connect to a server, networked servers using a proxy such as WaterFall or Velocity causes this to happen more frequently.
2. Get a potion effect, you also get potion effects when you die
3. All players kicked

## Links
[JEIDSl](https://github.com/robertdroptables-mcmods/JEIDsIntegration/releases)

[Stoneblock Issue](https://github.com/Sunekaer/stoneBlock/issues/370) 
[Info From Waterfall Dev](https://github.com/PaperMC/Waterfall/issues/418)
[JustEnoughIDs Dev talking about the issue](https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/41)

**Comment by 123Kappa** [comment]
Thank you for ignoring this for months and then closing it without replying. 
What a waste of time to host that modpack <3

**Comment by oly2o6** [comment]
Was closed because I don’t have a fix that works across the board, I have seen other servers get around this and tell me that they got around this

**Comment by oly2o6** [comment]
Basically I got told it was fixed ages ago as other server owners when I asked them I got the reply that they sorted it out, I just didn’t close the issue at said time as I forgot about it, I am more than happy to continue this on discord if you are interested to see if there fixes would work for you.

**Comment by oly2o6** [comment]
https://i.imgur.com/f8EQLsX.png im sorry if downgrading to a 2year old mod was an option you thought i could do as a pack dev when there are other mods relying on it being latest, but you will be glad to here that the author is working on fixing your issues, until then i recommend you do not run sponge like 99percent of the Eula abiding modded community

**Comment by 123Kappa** [comment]
You lost me on the last sentence. :'D 
I recommend responding to threads. If you are unable to do that at least respond before you close them if you want to be respected in the moded community.

**Comment by 123Kappa** [comment]
Also it's pretty obvious that you didn't even read my post. The issue is not with Sponge it is with Bungeecord/Waterfall. 
Hell, I haven't even mentioned sponge in my post. 
The modpack works fine in a sponge enviroment without bungeecord as its proxy.

**Comment by 123Kappa** [comment]
Stop talking out of your ass and be a respectful modpack creator. 
You dont even know if my servers follow EULA or not.

**Comment by oly2o6** [comment]
never said you were not in the 1%, and lets be honest this issue (even though i did try fixing it) is on the mod developer and/or bungeecord/waterfall to fix it, cant expect me to revert to a mod version that is 2 years old just so you do not have to do the extra work to make my pack work with your overcomplicated unnecessary server setup, i refuse to break current worlds for sponge, waterfall, bungeecord or otherwise and other pack devs would take the same stance, whilst other server owners spent around a day or 2 and got this to work back in december, but i guess i might aswell apologise for assuming waterfall required sponge because last time i checked it did, thank you good night and i hope the dev fixes your issue
