### ISSUE TITLE
[Suggestion] Please tone down the recipe for Vulpes Library machine structures

### ISSUE THREAD

**Issue by OmaiGrundles** [AllTheMods/ATM3-Expert#191]
The recipe for the machine structure causes a huge difficulty spike in this pack, especially considering that you need around **twenty-eight** of them for just one machine because they are used for almost every piece of the multiblocks.

## Expected Behavior
This pack had before now had a pretty simple difficulty compared to most 'expert' packs, which was a breath of fresh air compared to most of the recent expert packs as of late. A friend and me had been playing this for a couple weeks and had been enjoying it until this point.

## Current Behavior
The recipe is just a nightmare in bulk. All the other 'machine frame' recipes were fine because you only needed one for each machine, but as I mentioned before, the advanced rocketry stuff are multiblocks where you need 25+ of the machine structures **per machine**.

## Possible Solution
Make the individual machine controllers (precision assembler, etc) recipes more expensive, and return the machine structure to the vanilla recipe, or at least something cheaper. Actually, scratch that, the recipe for the input/output hatches you need for each machine is more than enough IMO

**Comment by rlnt** [comment]
I'll take a look into that and try to rebalance it.
Your possible solution sound good but I don't really get if you want us to adjust the controllers or the hatches.

**Comment by tjsd** [comment]
This is most likely in reference to the Plasma Core recipe that needs to be crafted manually that we already covered in discord.

**Comment by rlnt** [comment]
Solution for v1.6.0:
- plasma core is now automatable and a bit easier to craft
- machine structures now give 2 per craft instead of 1

**Comment by NurikSakura** [comment]
Plasma Core are automatable in the current CurseForge version using Machine Buffer from IC2 and Crafting Upgrdae, as it intended by the mod-dev. Just FYI.
