### ISSUE TITLE
[Important]Blood Magic copy items BUG

### ISSUE THREAD

**Issue by JackMeds** [AllTheMods/ATM3-Expert#192]
## Expected Behavior
This BUG can copy anything!!!
## Current Behavior
cpoy
## Possible Solution
Add it into 'carry on' config blacklist
## Steps to Reproduce
1.Place a arcane ashes on the ground
https://imgur.com/lF0ajA1
2.Prepare a shulker box with items in it.
https://imgur.com/jgpeA9M
3.Align the ashes and click the right mouse button
4.Pick it up by use the 'carry on' mod
https://imgur.com/6kI3tRa
5.NOW YOU CAN COPY ANYTHING by long right click

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0
