### ISSUE TITLE
elementiumprint recipe bug

### ISSUE THREAD

**Issue by W0297** [AllTheMods/ATM3-Expert#195]
![79F977A7-C52F-466A-892C-23A425CC54EF](https://user-images.githubusercontent.com/59212989/71427306-3d438e00-26f2-11ea-8fec-f65b9379e5d6.png)
I guese this is a wrong recipe.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by TheGoldCrayon** [comment]
will be fixed in next update

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0
