### ISSUE TITLE
IC2 Armor Client Disconnect

### ISSUE THREAD

**Issue by mtimyself** [AllTheMods/ATM3-Expert#196]
Hybrid Solar Helmet
Ultimate Hybrid Solar Helmet

Disconnects client on equip and prevent the client from re-joining.

**Comment by Trinsdar** [comment]
could you provide a crash log please? @mtimyself

**Comment by mtimyself** [comment]
The user said no crash report was written. On the server side it is a generic "Can't tick entity" error.

**Comment by mtimyself** [comment]
Updated with new info. Apparently client does not crash but disconnects.

**Comment by Trinsdar** [comment]
ok I fixed it in advanced solars classic and released a new build

**Comment by TheGoldCrayon** [comment]
mod will be updated in next pack release

**Comment by TheGoldCrayon** [comment]
mod updated in 1.4.0
