### ISSUE TITLE
Astral Sourcery Illumination Powder Won't Craft, due to Astral Progression Broken due to Pack.

### ISSUE THREAD

**Issue by Rixxaw** [AllTheMods/ATM3-Expert#197]
## Expected Behavior
When you right click on the Luminous Crafting Table with the correct Recipe it should make 16 Illumination Powder as per JEI.

## Current Behavior
The table does nothing when you click on it with the wand. and have the correct recipe.

## Possible Solution
I assume the Luminous Crafting Table Recipe tweak should be removed so that normal Progression can happen with Astral as the current issue is known and goes back to 2018 : [Issue from Sevtek](https://www.reddit.com/r/feedthebeast/comments/8dz9q1/sevtech_luminous_crafting_table_not_working/)

## Steps to Reproduce
1.  Progress to Stage 3.
2.  Craft the Luminous Crafting Table.
3.  Place it down with view of Sky and 1/2 or greater starpower.  At Night or under a Rock Crystal found in the world.
4.  Craft the Resonating Wand.
5.  Put 4 Glowstone and 1 Aquamarine in the table as per the Illumination powder recipe.
6. Right Click the table with the Wand. 
7.  Your Astral book will also show Exploration is not unlocked and there appears to be no path forward in Astral since you didn't create the table in the expected way.

## Detailed Description
Astral Sorcery has its own progression system, and requires you to craft the Luminous Table using the method described in the book, and not the method JEI requires.  Thus you never unlock the Exploration Tab in the book and can't make the illumination powder.  Even with a Table lit by a Rock Crystal with full star power the recipe is not craft-able.  The Work around is to go in to creative , and give yourself the Scroll of Written Expertise, which essentially unlocks the entire mod.  This work-around wouldn't work on Servers, or for players that refuse to go in to creative.

**Comment by Uimori** [comment]
Just an FYI because I ran into this problem too...

If you craft the Luminous Crafting Table in say a Modular Storage or Storage Tablet, the behavior described above happens...

However, if you craft it in a vanilla crafting table under a floating crystal like you normal would in Astral Sorcery, then you unlock the progression thus allowing you to craft the Illumination Powder.

Didn't test crafting it in a vanilla crafting table elsewhere.

**Comment by Trinsdar** [comment]
there might be a way around this using ct's [IRecipeAction](https://docs.blamejared.com/1.12/en/#Vanilla/Recipes/Crafting/Recipe_Functions/#irecipeaction)

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0 added reward command to give you basic research
