### ISSUE TITLE
[1.3.0] Thaumcraft Mundane Ring not craftable

### ISSUE THREAD

**Issue by Uimori** [AllTheMods/ATM3-Expert#198]
Pack Version: 1.3.0

## Expected Behavior

Mundane Ring should be craftable

## Current Behavior

The ring looks craftable and JEI adds the items (only 3 gold plates instead of 4), but nothing crafts.

## Possible Solution

The CraftTweaker script has a typo in it.

Scripts/Magic/Thaumcraft.zs, line 203
"ore:goldPlate" should be "ore:plateGold"

**Comment by TheGoldCrayon** [comment]
will be fixed in next update

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0
