### ISSUE TITLE
Game wont start and crashes on load

### ISSUE THREAD

**Issue by PizzaRollsGod** [AllTheMods/ATM3-Expert#199]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Industrial Craft Classic (ic2)

^ This is the error I get
## Expected Behavior

The game runs

## Current Behavior

The game doesnt run

## Steps to Reproduce

1. Download mod pack on Twitch
2. Click play
3. Have it try to start for 10 minutes
4. It crashes

## Log

https://gist.github.com/PizzaRollsGod/99cecea27897ef6c0eec2c65d1fbf2b1/131d9d2f5197c44c108b5644cc90d39d275ae0d3

## Detailed Description

I propose a solution

**Comment by Uimori** [comment]
It says "java.lang.OutOfMemoryError" and looks like you only have around 3gb allocated.

Did you try increasing the amount of memory you allocate to minecraft?

**Comment by PizzaRollsGod** [comment]
that was it thanks
