### ISSUE TITLE
Vitrified Sand Picks Cannot be Repaired.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#20]
I am unable to repair my tinkers vitrified pick. Molten clay cannot be used to make an ingot cast using clay brick, porcelain brick, or an iron ingot. Searching JEI shows no vitrified ingots. If you create a second vitrified pick head it will not repair the pick eiither.

**Comment by SpeedSlider** [comment]
As an additional note when crafting a flint pick head to replace/revert the pick the pick will still be broken until you use additional flint to repair it once the head has been swapped. So tinkers mechanic is not to use tool parts to repair an item.

**Comment by oly2o6** [comment]
Sharpening kit has recipe
