### ISSUE TITLE
ASTRAL RITUAL NOT WORKING

### ISSUE THREAD

**Issue by sreekrishna5** [AllTheMods/ATM3-Expert#200]
## Expected Behavior

It is not tick accelerating and block

## Current Behavior

HOROLOGIUM RITUAL NOT WORKING

## Steps to Reproduce

1.
2.
3.
4.

**Comment by TheGoldCrayon** [comment]
Are you sure you're doing everything right? There are guides that explain what to do, as I'm not sure with AS rituals. If it's truly not working, it sounds more like an AS issue rather than a pack issue, as I don't think we've disabled it.

**Comment by sreekrishna5** [comment]
![2020-01-12_10 44 28](https://user-images.githubusercontent.com/40898266/72214469-a3207a00-3528-11ea-92f5-29a8933c648b.png)
tht ritual anchor is linked to an astral ritual that has a perfect crystal attuned to horologium
and none of the tile entites there is tick accelrated and the ritual is in range.As according to the config the ritual has a range of 16 and a potency of 1.0
