### ISSUE TITLE
Server timeout caused by a mysterious crash

### ISSUE THREAD

**Issue by Quizer9O8** [AllTheMods/ATM3-Expert#204]
## Expected Behavior
It should join the sever with no effort.

## Current Behavior
Whenever I join the server I play on it takes a so long it gives me a server timeout.

## Possible Solution
N/A

## Steps to Reproduce

1. Go to Multiplayer
2. Join memenetwork.net
3. select ATM3E
4. Either you get in or you won't.

## Log
https://pastebin.com/zb62P8rd

**Comment by TheGoldCrayon** [comment]
As stated in the discord, this is an issue between your player and the server. When getting a crash when connecting to the server, always contact the server admins first, especially when you were able to connect previously, as that's where the error usually occurs.
