### ISSUE TITLE
Netherending Ores not being doubled in Thermal Expansion Machines

### ISSUE THREAD

**Issue by ixanza** [AllTheMods/ATM3-Expert#205]
The Netherending Ores Nether and End Ores can be smelted in a regular furnace for 2 ores each or put in the macerator for 4 dust each. However when smelting them in a redstone furnace they only provide 1 ore and when pulverizing though they give 3 dusts it is still less than smelting and getting 2 ores then pulverizing it for 4 dusts or just throwing it in  the macerator for 4 dusts

## Expected Behavior

It should follow the default furnace recipe or be properly doubled  like the macerator does

## Current Behavior

It doesn't follow the default furnace recipe or properly doubled

![image](https://user-images.githubusercontent.com/5535758/71775494-90ec8c00-2fbc-11ea-9f41-6ecf5aea6da3.png)
![image](https://user-images.githubusercontent.com/5535758/71775495-98139a00-2fbc-11ea-85c2-981445b0c312.png)

![image](https://user-images.githubusercontent.com/5535758/71775497-9f3aa800-2fbc-11ea-947e-55073afe05ef.png)
![image](https://user-images.githubusercontent.com/5535758/71775500-ab266a00-2fbc-11ea-9ecd-0eefa5e3e9e5.png)

## Steps to Reproduce

1. Get Netherending ore
2. Put in redstone furnace
3. Get 1 ore instead of 2

**Comment by oly2o6** [comment]
this is honestly an issue for the devs and with mod devs jumping versions i dont see it being fixed
