### ISSUE TITLE
RF not converting to EU(Mekanism cables powering ic2 machines)

### ISSUE THREAD

**Issue by sreekrishna5** [AllTheMods/ATM3-Expert#207]
## Expected Behavior

RF not converting to EU(Mekanism cables powering ic2 machines)

## Current Behavior

Mekanism cables connecting to ic2 machines but not transfering any power

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Trinsdar** [comment]
I believe it was disabled as it was more trouble than it's worth

**Comment by sreekrishna5** [comment]
K
