### ISSUE TITLE
Recipe Bug: Manganese ingot (by NuclearCraft) without recipe.

### ISSUE THREAD

**Issue by lucasdoniytb** [AllTheMods/ATM3-Expert#208]
This blocked a progression.

**Comment by bomber12309** [comment]
the recipe is there, you have to crush rhodochrosite (use the rock crusher to get it), then smelt the rhodochrosite dust into manganese oxide dust, smelt that into manganese oxide ingot, smelt that again into a manganese ingot

**Comment by lucasdoniytb** [comment]
ok, Thank you.
