### ISSUE TITLE
Cinderpearls (Thaumcraft plant) Break Nether Progression

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#21]
Thuamcraft includes cinderpearls as world gen in deserts. Cinderpearls create blaze powder in a crafting table which allows crafting of fire charges which can be used to light a nether portal. A nether portal can be created with ten clay buckets of lava and one clay bucket of water. All you have to do is place a form and place one bucket of lava at a time in the form and use the water to turn it into obsidian. Obsidian has a world mining level of manasteel. Once the correct configuration of the portal is made with this method then you strick the portal with a fire charge and it lights the portal. This is a vanilla trait and no cheats were used.

**Comment by oly2o6** [comment]
Fixed
