### ISSUE TITLE
Wireless crafting terminal bug

### ISSUE THREAD

**Issue by sreekrishna5** [AllTheMods/ATM3-Expert#210]
## Current Behavior

The wirelss crafting terminal is working without even placing the wireless access point

![2020-01-14_08 47 16](https://user-images.githubusercontent.com/40898266/72311385-814f0080-36aa-11ea-96fb-6c2c74d343c6.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by oly2o6** [comment]
i tried this and it didnt happen for me, going to assume it was just a weird issue on your part if it happens on a different world or pack contact the dev
