### ISSUE TITLE
Blood Magic Speed Runes Bugged

### ISSUE THREAD

**Issue by Chocopuffs** [AllTheMods/ATM3-Expert#211]
I have done some testing with speed runes because i have 50 of them on my altar and there is no difference in speed. 

## Expected Behavior
When you add speed runes to your altar it should speed up crafting, 50 speed runes should give 11x craft speed.

## Current Behavior
Testing proved by creating slate in other people's Blood altar then looking at it with "Seer's Sigil" which shows the progress of the current item in the altar and what consumption the item is using. the consumption rate didnt change when tested on several altars. i also broke my altar from T5 down to T2, then built back up to T5 to see if i was hitting a hard cap, there was still no changes.

## Possible Solution
I have reached out to Blood magic devs on discord but no official response, a fanboy did try and help me and after looking at my screenshots he was perplexed.
This could be a config issue (but i have no real clue) please fix.
could also be an animus issue

## Steps to Reproduce
1. as stated, reconstructed my altar
2. tested on several other altars
3. No difference.

## Detailed Description
I'm proposing oly is bad.

**Comment by bomber12309** [comment]
just tested in solo and they work fine. i made a reinforced slate in a t2 altar with blank runes and one with speed runes, the regular altar used 5 LP/t (as intended), the one with speed runes used 9 LP/t (80% faster, as intended).

i did notice that the text under TOP said 5 LP/t consumption for both, but you have to look at the blood magic text, on the 4th line.
