### ISSUE TITLE
Dagger of Sacrifice Not working in mechanical user

### ISSUE THREAD

**Issue by sreekrishna5** [AllTheMods/ATM3-Expert#212]
## Expected Behavior

dagger of sacrifice in mechanical user to produce lp

## Current Behavior

The dagger of sacrifice is not working inside a mechanical user ,it is juz punching the mobs to death.This is only possible way to automate lp for rituals as the well of suffering ritual is disabled
and u need automate lp to get the other type of crystals

## Steps to Reproduce

1.
2.
3.
4.

**Comment by oly2o6** [comment]
Well of suffering was replaced with culling I believe? There is a replacement I’m just unsure on its name (lag reduction as it isn’t skills mobs)
