### ISSUE TITLE
ME Circuit Etcher turns into Fluix Aggregator wtih Carry On

### ISSUE THREAD

**Issue by Dilzi** [AllTheMods/ATM3-Expert#213]
After picking up and placing an [ME Circuit Etcher] with Carry On, it turns into a [Fluix Aggregator]

## Expected Behavior
Picking up and placing the Circuit Etcher should place a Circuit Etcher

## Current Behavior
Placing the Circiut Etcher with Carry On transforms it into a Fluix Aggregator

## Steps to Reproduce
1. Place an ME Circuit Etcher on the ground
2. Pick it up with Carry On (Shift-right click with an empty hand)
3. Place the ME Circuit Etcher back onto the ground

**Comment by phantamanta44** [comment]
should be fixed by a combination of phantamanta44/libnine@07ea51301d98c37bfabfc589a061089da1434a52 and phantamanta44/Lazy-AE2@074b252d2b3a411dbe0af73b19fa5f077e4c7a7d. just have to wait for curseforge to approve the new versions
