### ISSUE TITLE
Quest (100) alloying the basic way seems redundant

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#22]
Quest (8) Let's make some porcelain has you craft two melters three heaters and an alloy tank. Making an additional alloy tank and heater isn't useful without a third melter and an additional heater so you can have two different alloyies going at the same time.

My recommendation would be to remove the porcelain alloy tank and one heater from quest (8) lelt's make some porcelain so that quest 100 makes sense or just remove quest 100.

Also, quest 100 misspells fluids as "bluid".

**Comment by oly2o6** [comment]
this was fixed..?

**Comment by SpeedSlider** [comment]
I just got to it in 1.2.0 alpha single player.

**Comment by oly2o6** [comment]
/bq_admin default load
always do that after an update to the book
