### ISSUE TITLE
Incorrect amount of items in recipes makes them uncraftable

### ISSUE THREAD

**Issue by NurikSakura** [AllTheMods/ATM3-Expert#227]
Got to a stage, where I need to craft Plasma Cores from IC2C, yet the recipe in JEI shows I need 8 Magnets, 16 Advanced Alloys and a Plasma Cell. Which is a bit weird for a crafting table recipe. I thought it to be a visual bug, yet trying to insert the recipe into AE2 auto-crafting does not produce the result. I tried to craft it in the crafting bench myself with only one item in slots, yet it is not a valid recipe. If I put all the items, it does not show immediately, but after closing/opening the table it shows up.

Here are the screenshots and a video: https://imgur.com/a/AQZSua9
The issue occurs both on server and in singleplayer - screenshots are from my server, video I tested in the same client in a singleplayer world.

**Comment by oly2o6** [comment]
These recipes are actually showing correctly, this is ic2c that does this and jei showing you need 8 magnets is actually the amount you need inserted into the slot

**Comment by NurikSakura** [comment]
So all the Plasma cores are supposed to be crafted only manually? Which means anything that needs Plasma cores as part of their recipe can't be autocrafted also? Because none of available options for autocrafting does not support more then one item in a crafting grid.

**Comment by NurikSakura** [comment]
Nevermind, found some info on the issue tracker for IC2C. Apparently, this is how it is supposed to work. Welp, Industrial craft always had their own vision on how things should work. Yeah...
