### ISSUE TITLE
Seared bricks are broken.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#23]
There is no way to obtain seared bricks. The current recipe for seared stone requires you to pour a molten grout, clay and vitrified sand alloyed, over gravel to obtain a seared stone block. The molten grout cannot be poured into an ingot cast. The normal grout recipe requires clay, sand, and gravel so alloying the clay and sand alloy to be poured directly into a seared ingot doesn't make sense either.

Possible solutions: allow seared stone to be broken down into brick somehow. Perhaps using a flint tool. Additinoally, you could allow the ingots to be crafted by pouring over flint in a cast table since flint is derived from gravel? Maybe, another use for sharpened flint would be to combine in a crafting table with seared stone to make bricks?

**Comment by oly2o6** [comment]
its not unobtainable you can smelt the seared blocks down and recast them, will be adding a molten grout + flint shard recipe tonight
