### ISSUE TITLE
!Refined Iron Recipe Problem

### ISSUE THREAD

**Issue by glgzachattack** [AllTheMods/ATM3-Expert#231]
**Describe the bug**
When trying to produce Refined Iron it makes Steel instead.
one iron ingot in the top slot, one coal coke in the fuel slot, produced steel
JEI has both recipes listed.

**Expected behavior**
Only refined iron should be the output of the blast furnace.

**Screenshots & Logs**
https://gyazo.com/84098f1310d57c006ae01d0e13ed18b6

**Versions (please complete the following information):**
 - Modpack version: v1.6.0
 - used Launcher Twitch App

**Additional context**
I have optifine installed as well
Verified the bug with Discord helper admin. (Sverd)

**Comment by glgzachattack** [comment]
When trying to produce Refined Iron it makes Steel instead. 

one iron ingot in the top slot, one coal coke in the fuel slot, produced steel 

JEI has both recipes listed. 

https://gyazo.com/84098f1310d57c006ae01d0e13ed18b6

**Comment by glgzachattack** [comment]
Version 1.6.0 through the Twitch App
I have optifine installed as well

**Comment by glgzachattack** [comment]
Verified the bug with Discord helper admin. (Sverd)

**Comment by Phant0mKnight** [comment]
Same issue occurred to me, happens with both blocks of iron becoming blocks of steel, and ingots of steel from ingots of iron. However, ingots of steel are from thermal foundation, and blocks of steel are from tinker's.

**Comment by tjsd** [comment]
Have verfied this bug on 1.6.0 with iron ingot + charcoal, iron block + charcoal.
These lines are missing and should be added to immersiveengineering.zs in the Blast Furnace section.

`mods.immersiveengineering.BlastFurnace.removeRecipe(<immersiveengineering:metal:8>); `
`mods.immersiveengineering.BlastFurnace.removeRecipe(<immersiveengineering:storage:8>);`

**Comment by rlnt** [comment]
The new unwanted recipe is made by UniDict since it's unifying refined iron and steel now. Thanks for the report. I will fix this asap.

**Comment by rlnt** [comment]
If anyone wants this change before we push the new hotfix which could take a while, replace your current scripts folder (on client & server) with the one in the zip file.
[scripts.zip](https://github.com/AllTheMods/ATM3-Expert/files/4587584/scripts.zip)
