### ISSUE TITLE
Refined iron ingot

### ISSUE THREAD

**Issue by DrTr0ma** [AllTheMods/ATM3-Expert#233]
Hello,

In JEI the only way to obtain refined iron ingot (to craft wire cutters) is from the blast furnace from immersive engineering but mine is giving me steel ingot from thermal foundation.

Am I missing something ?

(I'm playing the last version)

**Comment by rlnt** [comment]
This bug is known and was already reported here: https://github.com/AllTheMods/ATM3-Expert/issues/231

It has been fixed already but we are waiting for the owner of the modpack to release the hotfix. Click on the link and go to the last comment. I wrote how to fix it temporarily there.
