### ISSUE TITLE
Advanced crafting table recipe

### ISSUE THREAD

**Issue by Confluxes** [AllTheMods/ATM3-Expert#234]
**Describe the bug**
The advanced crafting table needed to make Industrium alloy is currently unable to be crafted due to the requirement of ender ingots which require a vat to make and you cannot make the vat without Industrium. So currently you are unable to progress past tier 3

**To Reproduce**
1. Attempt to make advanced crafting table
2. See that it is unobtainable 

**Expected behavior**
A recipe that works for ender ingots without the vat or a different recipe for the table

**Versions (please complete the following information):**
 - 1.6.1
 - Twitch

**Comment by rlnt** [comment]
Fixed in https://github.com/AllTheMods/ATM3-Expert/commit/80fa185adaf7a2cc6195e8f3f051af667150530a

**Comment by rlnt** [comment]
If you want to manually apply this patch before the new hotfix comes out, replace your scripts folder on client and server with this one.
[scripts.zip](https://github.com/AllTheMods/ATM3-Expert/files/4610159/scripts.zip)
