### ISSUE TITLE
Server files for 1.6.1 broken

### ISSUE THREAD

**Issue by audioblaster** [AllTheMods/ATM3-Expert#239]
Tried to start a server, both from a dedicated server (i copied over the files via FTP) then tried starting from my own PC, still got the same error message when trying to connect with my client. Nothing usefull as far as i can tell in server log.
![error1 client](https://user-images.githubusercontent.com/63523203/82098333-128bbd80-9705-11ea-899a-1dd29762c408.png)

![error2 server](https://user-images.githubusercontent.com/63523203/82098343-161f4480-9705-11ea-8b01-4e5a21dd2db7.png)

**Comment by audioblaster** [comment]
To clarify, i have also tried re-downloading the server files and unzipping them again, nothing works. Was of course downloaded from Curse/Twitch

**Comment by rlnt** [comment]
We're having multiple people playing on v1.6.1 right now. No one reported this so far. The author who submits the server files has to take a look at that. Thanks for the report!

**Comment by oly2o6** [comment]
Replace the configs in your server with the ones on your client, this is a config desync issue
