### ISSUE TITLE
Quest Book Issues

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#24]
Two quests currently want other pre-req quests that don't exist

## Current Behavior

![image](https://user-images.githubusercontent.com/51287780/59170576-4fbaf900-8b0d-11e9-9fd9-2e9e98d602d7.png)

![image](https://user-images.githubusercontent.com/51287780/59176664-c9f87700-8b27-11e9-9ae6-72e9b6087c44.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by oly2o6** [comment]
Shit
