### ISSUE TITLE
Can`t separate jetpack from plate.

### ISSUE THREAD

**Issue by demethan** [AllTheMods/ATM3-Expert#247]
**Describe the bug**
A clear and concise description of the bug you found.

we are on version 2.2.14

I have the energetic jetpack and I want to upgrade it. Normally I would put in the grid to separate the plate from the jetpack.  it doesn`t show in the output of the crafting grid. 

**To Reproduce**
1. put jetpack in crafting grid.
2. nothing in the output. 

**Expected behavior**

I should get both items in my inventory after pulling out the jetpack off the output of the crafting grid. 

**Screenshots & Logs**
If applicable, add screenshots and/or logs to help explain your problem.

![image](https://user-images.githubusercontent.com/5810363/85641629-26f49b80-b65d-11ea-831b-2ee0fb7fce4d.png)

**Versions (please complete the following information):**
 - Modpack version: 2.2.14
 - used Launcher GDlauncher

**Additional context**
If you have any additional mods installed to the modpack even if it's just optifine, list them here.

**Comment by rlnt** [comment]
Version 2.2.14?
This version does not exist on All The Mods 3 Expert.

**Comment by demethan** [comment]
Ooops my bad.   we are at version  All the Mods 3: Expert ( 1.7.0)

2.2.14 is simply jetpack`s version
