### ISSUE TITLE
Config Copy Request

### ISSUE THREAD

**Issue by Speiger** [AllTheMods/ATM3-Expert#248]
Hey. Thanks for putting IC2Classic into ATM-3-Expert.

I wanted to ask if we could take the Crops config you put in there and put them into the IC2Classic wiki so people could if they want it from there to make crop compat possible with the mods you already have made support?

Speiger

**Comment by oly2o6** [comment]
Yeah sure that’s fine, honestly kindof forgot how they were added as Trinsdar did all the work but if you can find where it was done go ahead 😅

**Comment by Speiger** [comment]
@oly2o6 it is in the IC2 Config folder. I found them thats why I asked.
Thanks for that.
