### ISSUE TITLE
Diamond Modifier on TiCon tools breaks progression

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#26]
Attaching a diamond as a modifier on a Tinker's pickaxe allows you to increase your mining level by 1 level. There *might* be a way to change that in the configs so you can keep the durability addition, but I'm not 100% sure.

**Comment by oly2o6** [comment]
ill look into normal tinkers configs and if i cant find a way to turn it off ill add another mod to do so
