### ISSUE TITLE
Blast Furnace Refined Iron Block Slag

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#27]
In the Crude Blast Furnace, when you make refined iron, 1 iron ingot turns into 1 refined iron ingot and 1 slag. However, 1 iron block turns into 1 refined iron block and still only 1 slag. I'm not sure if this is intended or not, but I know when steel is made in the blast furnace (in other packs of course as the recipes was removed here) a block would produce 9 slag.

**Comment by oly2o6** [comment]
Might change it to 3 as it has a big time difference and want a diminishing return
