### ISSUE TITLE
Iron Furnace Recipe

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#29]
When looking up the recipe for the generator from IC2C, I noticed that the recipe for the iron furnace can be made two ways. First, it can be made with 5 iron ingots and 1 furnace. Second, it can be made using just 8 iron and no furnace. 

Recommendation: remove both recipes and make a recipe for 5 refined iron and 1 furnace
Reason: The iron furnace is used in the recipe for the generator. If using the recipe with the iron furnace, you only need 3 refined iron instead of 8 when you use the machine block.

**Comment by oly2o6** [comment]
I’ll remove the 8iron into furnace recipe and keep the 5 iron and 1 furnace recipe
