### ISSUE TITLE
IC2C Metal Bender Recipe

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#30]
The recipe for the Metal Bender requires 3 iron plates. However, it seems like it will only accept Thermal Foundation iron plates, as it is not ore dictionaried with other ones, such as the plates from RailCraft

**Comment by oly2o6** [comment]
I’m not sure what to do with the raikcraft plates currently they are causing a lot of issues

**Comment by oly2o6** [comment]
Removing railcraft rolling of plates due to its unification not correctly operating, and removing their plates from dungeons
