### ISSUE TITLE
Hardened Glass Quest 

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#32]
Quest #78. The quest calls for the player to craft hardened glass. However, it's not detecting that I made it. I suspect the reason is that it's a crafting quest, and it shows a green checkmark by a furnace and crafting table, so I'm guessing that those are the only ways it'll detect that you "crafted" it. But the quest comes after the one to make an induction smelter, so that's how I made it. 

I'd suggest changing the quest to a detection quest rather than a crafting quest.

**Comment by oly2o6** [comment]
sorrry
