### ISSUE TITLE
Storage Tablet/Quest Book Crafting issues

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#33]
It seems that when the quest book has a crafting quest, if you make it in a storage tablet, and probably the storage scanner as well, the book doesn't recognize you made it. To help, I'd suggest turning most of the crafting quests into detection quests. In my opinion, there isn't much need for crafting quests over detection ones, since most of the things you have that need to be crafted can't be found as loot, so you *have* to craft them.

**Comment by oly2o6** [comment]
I tried to swap them all over I must have missed a few in earlier tiers
