### ISSUE TITLE
Thermal thinks Leather is food?

### ISSUE THREAD

**Issue by cplir-c** [AllTheMods/ATM3-Expert#35]
## Expected Behavior

I'd expect the trivection chamber augment to not double the leather output of smelting rotten flesh.

## Current Behavior

Instead, it does.
![vgy.me](https://i.vgy.me/7SQP8m.png)`

**Comment by oly2o6** [comment]
That’s not double that’s 4 =2

**Comment by cplir-c** [comment]
![vgy.me](https://i.vgy.me/uKpNnp.png)

**Comment by oly2o6** [comment]
It’s still not terrible, and that’s not really a pack issue it’s a dev issue
