### ISSUE TITLE
Black Quartz not genning in Atum

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#37]
I've run into an issue where the next quest requires me to mine black quartz ore, but I haven't been able to find any in the Atum. First, I'm not sure exactly what level to mine at, since the JEI plugin for world gen isn't showing any black quartz. Second, I think the reason could potentially be that black quartz isn't set to generate at all. I haven't looked in the mining dimension yet, but I had a look in the files for the pack and saw it was blacklisted only in the overworld. However, I looked and couldn't find a spot where it was set to spawn in the Atum dimension. Granted I'm not a pack dev, so I don't know exactly where this would be. Maybe a little hint in the guide book would be helpful for that quest as well, if need be.

**Comment by drizzs** [comment]
Issue solved in next update! Retrogen will allow for spawning without reset!
