### ISSUE TITLE
Reinforced Slate not craftable

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#38]
I know Drizzs said at one point that Blood Magic progressing is somewhat broken, so this is more of just a reminder or to have something written down. The Reinforced Slate from Blood Magic isn't craftable. It's the tier 2 slate, after Blank Slate. The recipe for it in Blood Magic is supposed to be a Blank Slate plus some amount of LP in a tier 2 altar, but it's not showing as a recipe in JEI and it's not working for me.

**Comment by oly2o6** [comment]
Fixed
