### ISSUE TITLE
Enhancement: Add manuals to Akashic Tome by default.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Expert#4]
## Expected Behavior

ATM3 and ATM3:Remix have the manuals loaded by default into an Akashic Tome.

## Current Behavior

ATM3:Expert (in Dev) does not have manuals in tome by default so single player world starts with 8 manuals taking up inventory space.

## Possible Solution

Add all in game manuals to the Akashic Tome.

## Steps to Reproduce

1. N/A
2.
3.
4.

## Log

N/A

## Detailed Description

As described above.

**Comment by oly2o6** [comment]
It is kindof done just missing a few books and has 1 in from a removed mod so was not included in current version

**Comment by SpeedSlider** [comment]
Cool.

**Comment by oly2o6** [comment]
currently works but needs more books adding
