### ISSUE TITLE
Loot Table issues

### ISSUE THREAD

**Issue by TheGoldCrayon** [AllTheMods/ATM3-Expert#43]
I'll keep this list updated with what I find in loot tables, but I rtp'd and went mining, stumbled upon a dungeon of sorts undergound. So far I have found:

Railcraft steel pickaxe
Botania manasteel ingot
IC2C tiny pile of plutonium
Railcraft steel leggings
Random Things spectre coil nr. 153 (free 128 rf/t)

I found all of these things break progression. If I find more, I'll reply with what I find.

**Comment by TheGoldCrayon** [comment]
Ender IO dark steel, the Ender, dark steel boots
Railcraft steel sword

**Comment by drizzs** [comment]
Fixed in next update
