### ISSUE TITLE
Essentia Smeltery Uncraftable

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#44]
## Expected Behavior
 For the essentia smeltery recipe to work

## Current Behavior
It shows the vis crystals and vis in the aura needed, but won't craft. I have the research (the thaumonomicon requires me to craft the smeltery to even progress in the alchemy tab), I have the right recipe, I have the vis crystals & aura but it won't craft. JEI is telling me I'm missing "ESSENTIASMELTING".

## Possible Solution
I _believe_ the research assigned to the recipe is wrong- every other recipe has a name fitting the entry in the thaumonomicon: "Warp, Basic Auromancy, Essentia Tubes", but this says ESSENTIASMELTING instead of Essentia Smelting.

## Steps to Reproduce
1. Follow the thaumonomicon
2. Reach the Essentia Smelting chapter
3. Try to craft the essentia smeltery

![2019-07-02_10 20 05](https://user-images.githubusercontent.com/52458743/60520248-0cd6e600-9cb3-11e9-97c5-cc0be798f37d.png)
![2019-07-02_10 20 12](https://user-images.githubusercontent.com/52458743/60520249-0cd6e600-9cb3-11e9-97a2-d21b2758db79.png)
![2019-07-02_10 20 15](https://user-images.githubusercontent.com/52458743/60520252-0d6f7c80-9cb3-11e9-94c6-56dd1dd1c68e.png)

**Comment by drizzs** [comment]
Solve in update, had wrong research issue resolved
