### ISSUE TITLE
Loot table Simple_dungeon is incorrect

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#47]
Loot table simple_dungeon is wrong. Items that do not belong in there still spawn in them.

To check loot table: /setblock ~ ~ ~ minecraft:chest 2 replace {LootTable:"chests/simple_dungeon"}
![2019-07-12_03 22 21](https://user-images.githubusercontent.com/31729663/61095626-82ca1280-a454-11e9-9e09-627df38a2ddd.png)

**Comment by drizzs** [comment]
Still needs work.
