### ISSUE TITLE
Vitrious Sand Pickaxe has nothing to repair it

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#5]
## Expected Behavior
Should have something we can use to repair it. Also should have more durability than flint since its better quality?

## Current Behavior
Does not repair with sand or compressed sand, has half the durability of flint.

## Possible Solution
add Molted Vitrious sand to Block in a casting basin to give us something to use to repair it with.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by oly2o6** [comment]
Fixed
