### ISSUE TITLE
(QoL) Akashic Tome, inventory books

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#50]
The mod Akashic Tome is in here, To prevent a full inventory at start maybe add all the other books you spawn with in the Akashic tome, and remove them from started inventory/spawn inventory.

![image](https://user-images.githubusercontent.com/31729663/61095973-17814000-a456-11e9-9659-068960dff813.png)

**Comment by Darkere** [comment]
Missing from akashic tome:
- Digital Guide
- Questbook !!!
- Actually addtions
- Extended crafting guide
- logistics pipes
- ATM recipes guide??
