### ISSUE TITLE
Molten Vitrified Sand has a space in front of it in the name.

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#53]
There is a space in front of Molten Vitrified Sand

![image](https://user-images.githubusercontent.com/31729663/61096517-2832b580-a458-11e9-96e5-fb06164d665f.png)

**Comment by VeyezX** [comment]
Also with the bucket version.

![image](https://user-images.githubusercontent.com/31729663/61096553-4e585580-a458-11e9-83dd-3ee6201954d6.png)

**Comment by oly2o6** [comment]
fixed in next update
