### ISSUE TITLE
Duplicated Crafting Recipe: Iron Furnace

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#55]
The recipe with 8 iron makes something else.
![image](https://user-images.githubusercontent.com/31729663/61097385-7ac1a100-a45b-11e9-9a18-76f9b790def3.png)

![image](https://user-images.githubusercontent.com/31729663/61097394-801eeb80-a45b-11e9-8669-c9c6d1c4ffbb.png)

**Comment by drizzs** [comment]
What is this something else?

**Comment by oly2o6** [comment]
its used for quark iron walls i think, im going to remove the 8iron one again as it was one i missed (ic2c has to have recipes removed by ID in json and they all reloaded)
