### ISSUE TITLE
[Recipe] Induction Smelter top middle slot.

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#58]
Looks like the recipe for induction smelter is not correct. It wants the top middle slot to be any other machine to craft?

https://gyazo.com/08f0a5e24de762b25a31a440dddc566c

![image](https://user-images.githubusercontent.com/31729663/61132584-f6ebd100-a4bb-11e9-8645-6a24568289e2.png)

**Comment by oly2o6** [comment]
Yeah it’s not supposed to do that... lol
