### ISSUE TITLE
Quest log has lots of discrepencies 

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#6]
Quest Log is broken, Melter and Alloy tank Both have two quests that are identicle one before and after vitrious sand quest. Seared block quest also has two one in the quest before furnace and after furnace. Both quests are also broken as the Seared block quest is asking for a Furnace and the so is the furnace quest when you do 1 if breaks both.

## Expected Behavior
should only have 1 of each quest, should have seared blocks in the quest before Furnace and remove them from the quest After.

## Possible Solution
Change entries in quest book to suggestions above! or other alternatives!

**Comment by oly2o6** [comment]
All fixed, tried redoing a quest line i did not originally complete and messed up a few things, will be all fixed in latest version
