### ISSUE TITLE
[Recipe] Duplicated Recipe for Obsidian dust and Pulverized Obsidian

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#62]
if you put obsidian in Macerator it makes Obsidian Dust
![image](https://user-images.githubusercontent.com/31729663/61135292-9d86a080-a4c1-11e9-8f6d-56327467d945.png)

In the recipe it shows it should be Pulverized Obsidian (what is used in the most recipes)
![image](https://user-images.githubusercontent.com/31729663/61135325-abd4bc80-a4c1-11e9-83ca-ca5610708ccd.png)

**Comment by VeyezX** [comment]
Maybe also check the other recipes for the pulverized stuff (Charcoal, Copper, Silver, etc etc)

**Comment by oly2o6** [comment]
charcoal would maybe be the other one

**Comment by VeyezX** [comment]
Pulverized charcoal is missing recipe for Macerator

![image](https://user-images.githubusercontent.com/31729663/61135763-9318d680-a4c2-11e9-8540-9ce55bde8949.png)

Macerator makes another Charcoal dust (ic2 version)
![image](https://user-images.githubusercontent.com/31729663/61135800-a1ff8900-a4c2-11e9-8bc3-c042622d5212.png)

**Comment by oly2o6** [comment]
fixed in next dev
