### ISSUE TITLE
[World-Gen] Mining dimension ore generation

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#63]
To many ores, To big of veins, Nether Draconium, Immersive engineering ores, 

![image](https://user-images.githubusercontent.com/31729663/61136490-0ff88000-a4c4-11e9-9f51-ca414a63d45f.png)

![image](https://user-images.githubusercontent.com/31729663/61136500-138c0700-a4c4-11e9-9923-3b70474ca3e5.png)

**Comment by drizzs** [comment]
Mining dimension is not controlled by cofhworld. Do you know which dim it is and i'll fix this.
