### ISSUE TITLE
Botania recipe pixie dust not working

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#67]
Elven Quartz is not getting accepted in the portal.

![image](https://user-images.githubusercontent.com/31729663/61163968-e6664580-a511-11e9-9e3d-27e0628e517e.png)

![image](https://user-images.githubusercontent.com/31729663/61163973-e9f9cc80-a511-11e9-94f3-6f067e94bf3c.png)

**Comment by drizzs** [comment]
Fixed in update
