### ISSUE TITLE
[1.1.6.1] Recipe in Thaumcraft.zs errors (railcraft items still in)

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#70]
![image](https://user-images.githubusercontent.com/31729663/61175012-b6b64c80-a5a8-11e9-8d7f-4e0c1beb00f9.png)

**Comment by drizzs** [comment]
Haters - Everyone last one of you! UGH UGH UGH UGH This is bad.

**Comment by oly2o6** [comment]
fixed
