### ISSUE TITLE
[Quest] Wrong item quest: Flint it up

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#71]
Quest is about making a Flint axe, it shows a wooden axe in the questbook.

![image](https://user-images.githubusercontent.com/31729663/61175065-ae124600-a5a9-11e9-8c3f-db26bd453371.png)

![image](https://user-images.githubusercontent.com/31729663/61175092-13663700-a5aa-11e9-8e1f-e3e0bc152039.png)

**Comment by oly2o6** [comment]
Fixing it now
