### ISSUE TITLE
[Recipe] Iridium plate missing recipe for ic2c

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#76]
Iridium plates cant be made in ic2c: Metal Bender and Roller. While every other plate can
![image](https://user-images.githubusercontent.com/31729663/61175608-d6eb0900-a5b2-11e9-8b96-005062af3388.png)
![image](https://user-images.githubusercontent.com/31729663/61175612-dce0ea00-a5b2-11e9-985f-3492e543f2bf.png)

**Comment by oly2o6** [comment]
That has to be a mod issue, I’ll look into it

**Comment by Trinsdar** [comment]
It was mainly because by default it breaks balance of ic2 iridium plates, especially when gtclassic is loaded. You can just add the recipe to the roller, after which it will be auto added to the metal bender

**Comment by oly2o6** [comment]
dont think im going to be using those iridium plates anyways, as ic2c has the more expensive ones, and planned to make them worse than they are
