### ISSUE TITLE
[Generation] Slime island spawn rate

### ISSUE THREAD

**Issue by VeyezX** [AllTheMods/ATM3-Expert#77]
Maybe downscale the spawnrate of slime islands.

![image](https://user-images.githubusercontent.com/31729663/61185044-9cd24380-a654-11e9-8f4b-1dc2bfa9c702.png)

![image](https://user-images.githubusercontent.com/31729663/61185053-b4113100-a654-11e9-99cd-2c9224ff8f6a.png)

**Comment by drizzs** [comment]
Fixed in next update
