### ISSUE TITLE
Impossible to get first copper cables

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#87]
hiya, it's impossible to get uninsulated copper cables- the 2 ways are from the extruder and the metal bender. 
The extruder requires coils, which require uninsulated copper cables, which would need an extruder, so that doesn't work.
And to make them using the metal bender requires you to get the extruding press -> needs a blank press -> needs refined iron plates -> needs a roller -> needs coils -> needs uninsulated copper cables

## Expected Behavior
Pretty logical, there should be a way to get uninsulated copper cables without using uninsulated copper cables

## Current Behavior
You can't get uninsulated copper cables without having uninsulated copper cables in the first place

## Possible Solution
here are a few possible solutions-
- A possibly inefficient recipe to get uninsulated copper cables (ex. 1 copper plate + wire cutters);
- Change the coil requirement in the extruder
- Make it possible to make refined iron plates without a roller/metal bender (ex. smeltery or crafting hammer)

## Steps to Reproduce
![Screen Shot 2019-11-07 at 1 01 25 AM](https://user-images.githubusercontent.com/52458743/68363923-63897c00-00fa-11ea-8454-5851abc3d418.png)
![Screen Shot 2019-11-07 at 1 02 21 AM](https://user-images.githubusercontent.com/52458743/68363925-64baa900-00fa-11ea-9ecc-1f866dfebf4a.png)
![Screen Shot 2019-11-07 at 1 02 54 AM](https://user-images.githubusercontent.com/52458743/68363931-67b59980-00fa-11ea-86a2-ba117a04550f.png)

The same recipe "loop" is there with the metal bender, it's just a lot longer

## Detailed Description
I might be repeating myself here, but uh... make it possible to get uninsulated copper cables

**Comment by oly2o6** [comment]
fixed this issue by reimplementing cutter+plate
