### ISSUE TITLE
IC2C extras' Roller and Metal Bender making IC2C Extras plates

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#89]
The Roller and Metal Bender make IC2C extras plates instead of Thermal Foundation plates, and IC2C plates can't be used for certain recipes (ex. AA's iron casing).

## Expected Behavior
Those machines should be making thermal foundation plates instead of IC2C extras plates.

## Current Behavior
They make the IC2C plates, forcing you to use the smeltery (pretty inconvenient) or other late-ish game machines (pressurizer from nuclearcraft, rolling machine from adv rocketry, metal press from IE)

## Possible Solution
Change the output to Thermal Foundation plates.

## Steps to Reproduce
![Screen Shot 2019-11-07 at 7 32 39 PM](https://user-images.githubusercontent.com/52458743/68439409-7a30e100-0195-11ea-92d4-756688180784.png)
![Screen Shot 2019-11-07 at 7 32 55 PM](https://user-images.githubusercontent.com/52458743/68439413-7b620e00-0195-11ea-90a0-17b195a7b46b.png)
![Screen Shot 2019-11-07 at 7 33 17 PM](https://user-images.githubusercontent.com/52458743/68439415-7c933b00-0195-11ea-850c-6b18474c5741.png)

**Comment by oly2o6** [comment]
fixed in next dev version
