### ISSUE TITLE
[Mod Suggestion] Server Utils

### ISSUE THREAD

**Issue by Elrol** [AllTheMods/ATM3-Expert#91]
I have been working on this mod for a while now, and was hoping to see if I could see if you wanted to add it to this pack, or any other for that matter. 

Its a 1.14.4 utility mod, that adds lots of commands, color chat, ranks, permissions, and more. All of the commands have a set of configurations, all can be changed (replace /home with /base for example) permissions can be customized, delays and cooldowns can be as well. It also adds support to control the commands of minecraft and of every other mod. It is able to do this via a permission.json file in the config folder. It checks for the command node as specified, and if the player has the permission, they are able to use the command. 

The curse page is [here](https://www.curseforge.com/minecraft/mc-mods/server-utilities)

I am an active developer, and aim to resolve issues within 24 hours of the ticket being opened. That being said, if you decide to add it, and have any issues, I will have it fixed as soon as possible.

**Comment by Trinsdar** [comment]
If you can tell this pack is a 1.12 pack, not a 1.14 pack, so unless you backport it it's not even possible to be added. And i don't know if you could backport it as commands in 1.12 are quite a bit different from commands in 1.14
