### ISSUE TITLE
Add blast furnace recipes to the Arc furnace

### ISSUE THREAD

**Issue by bomber12309** [AllTheMods/ATM3-Expert#94]
The arc furnace, being an upgraded version of the blast furnace, should inherit its recipes (iron -> refined iron ingots, overgrowth seeds -> organic green & black dye, HOP graphite ingots -> black iron ingots and rich slag, quartz ingots -> cracked hot steel and rich slag)

It's also possible to make steel ingots the easy way in the arc furnace (iron + coke dust). I'm not sure if that's intended, since you still need a lot of steel to get the arc furnace (+ crusher + squeezer for the graphite rods). Just wanted to bring it up

**Comment by TheGoldCrayon** [comment]
fixed in 1.4.0
